### ISSUE TITLE
Добавление настройки

### ISSUE THREAD

**Issue by alexeytrifonoff** [alei1180/clockifytobitrix24#1]
Предлагаю, количество загружаемых из Клокифай записей перенести в настройки, что бы можно было этим количеством управлять, Иначе возникают ситуации, когда этого количества не хватает и не все записи попадают в битрикс.

**Comment by alei1180** [comment]
> Предлагаю, количество загружаемых из Клокифай записей перенести в настройки, что бы можно было этим количеством управлять, Иначе возникают ситуации, когда этого количества не хватает и не все записи попадают в битрикс.

Исправлено.
