### ISSUE TITLE
Не всегда загружается описание задач их Битрикс

### ISSUE THREAD

**Issue by alexeytrifonoff** [alei1180/clockifytobitrix24#2]
При загрузке времени в таблице не отображаются данные задачи их битрикс. Такое происходит не постоянно, а периодически, видимо связано с порциями получения записей их Битрикс

**Comment by alei1180** [comment]
> При загрузке времени в таблице не отображаются данные задачи их битрикс. Такое происходит не постоянно, а периодически, видимо связано с порциями получения записей их Битрикс

Исправлено.
