### ISSUE TITLE
Поле для номера задачи

### ISSUE THREAD

**Issue by phirosed** [alei1180/clockifytobitrix24#21]
Было бы неплохо вернуть поле для номера задачи обратно, чтоб получать время по одной конкретной задаче в одном месте, а не распыляться на несколько сервисов

**Comment by alei1180** [comment]
> Было бы неплохо вернуть поле для номера задачи обратно, чтоб получать время по одной конкретной задаче в одном месте, а не распыляться на несколько сервисов

Это уже реализовано в #16
