### ISSUE TITLE
Добавить выбор часового пояса

### ISSUE THREAD

**Issue by phirosed** [alei1180/clockifytobitrix24#44]
При работе битрикса на другом часовом поясе неверно работает кнопка получения времени.

Кейс:
1. Получаем время из клокифай
2. Выгружаем в битрикс
3. Время отмечается как выгруженное
4. Снова получаем время их клокифай
5. Время отображается как невыгруженное, возможна повторная выгрузка в битрикс, что приводит к задвоению

**Comment by alei1180** [comment]
@phirosed корректировка часового пояса строго указана в коде. Спасибо за обратную связь, вынесу ее в настройки на форму.

**Comment by alei1180** [comment]
@phirosed готово, доступно в последнем релизе [1.1.4](https://github.com/alei1180/clockifytobitrix24/releases/tag/ver1.1.4)
