### ISSUE TITLE
Добавить количество ошибок в заголовок страницы Ошибки

### ISSUE THREAD

**Issue by alexeytrifonoff** [alei1180/clockifytobitrix24#47]
Для удобства просмотра количества ошибок при закрытой страницы добавить количество строк в таблице ошибок в заголовок страницы ошибки
![image](https://github.com/user-attachments/assets/5a749514-e575-4eed-bdd3-054732cbc1f1)

**Comment by alei1180** [comment]
@alexeytrifonoff реализовано в версии [1.1.5](https://github.com/alei1180/clockifytobitrix24/releases/tag/ver1.1.5)
