### ISSUE TITLE
Подсказать, есть ли возможность синхронизации списка задач clockify с битрикс 24

### ISSUE THREAD

**Issue by karamazoffm** [alei1180/clockifytobitrix24#48]
Может быть есть такая возможность, чтобы получать номера и тему задачи. Или может быть подскажете какой-то способ, кроме ручного. Чтобы видеть актуальный список задач битрикса в таск-трекере

**Comment by alei1180** [comment]
@karamazoffm 
> Может быть есть такая возможность, чтобы получать номера и тему задачи.

Текущая обработка получает информацию (номер и название задачи) только по тем номерам задач, которые были затреканы в clockify.  Поэтому здесь не вижу смысла отображать все задачи по исполнителю.

> может быть подскажете какой-то способ, кроме ручного. Чтобы видеть актуальный список задач битрикса в таск-трекере

В [соседнем репозитории](https://github.com/Bayselonarrend/OpenIntegrations) коллеги, есть [библиотека](https://openintegrations.dev/docs/Instructions/Bitrix24/) для 1С, которая дергает методы битрикса, в том числе по задачам.

**Comment by karamazoffm** [comment]
Спасибо вам большое!
